http:
  routers:
    superfluffer:
      rule: "Host(`superfluffer.byldr.co`)"
      service: superfluffer
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: mytlschallenge

    superfluffer-deploy:
      rule: "Host(`githook.byldr.co`)"
      service: deploy-hook
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: mytlschallenge

  services:
    superfluffer:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"

    deploy-hook:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9000"
